# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#trigger:
#- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  displayName: Build Gradle
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
- task: SonarCloudPrepare@1
  displayName: Preparar Sonar CLoud
  inputs:
    SonarCloud: 'sonar-conexion2'
    organization: 'cfg-devops-usach'
    projectKey: 'CFG-DevOps-Usach_Microservicio-spring-CFG'
    scannerMode: 'Other' 
- task: CopyFiles@2
  displayName: Copiar archivos
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
        **/build/libs/*.jar
        **/build/**/*.xml
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: Publica artefactos
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: appJar
    publishLocation: 'Container'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-conexion2'
    organization: 'cfg-devops-usach'
    projectKey: 'CFG-DevOps-Usach_Microservicio-spring-CFG'
    projectName: 'Microservicio-spring-CFG'
    extraProperties: |
      sonar.coverage.jacoco.xmlReportPaths=$(Pipeline.Workspace)/appJar/build/reports/jacoco/test/jacocoTestReport.xml
  displayName: 'Jacoco Preparing Sonarqube Environment'
- task: Gradle@3
  displayName: 'Analyze current Branch'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: "sonarqube"
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Analysis Results'

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'sonar-conexion2'
    organization: 'cfg-devops-usach'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'appJar'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: Descarga Jar
    
- script: "mkdir -p build/libs; mv $(Pipeline.Workspace)/appJar/build/libs/ build/; chmod -R 555 build/libs"  
  displayName:  Se mueve JAR a carpeta raiz

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'
  displayName: Docker registry login
    
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'cristobalfajardo/devops-cristobal'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: latest
  displayName: Build Image

- task: Docker@2
  displayName: Docker push
  inputs:
    containerRegistry: 'Docker'
    repository: 'cristobalfajardo/devops-cristobal'
    command: 'push'
    tags: 'latest'
- task: KubectlInstaller@0
  displayName: Install Kubectl
  inputs:
    kubectlVersion: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Connect kubernetes'
    namespace: 'default'
    command: 'login'
- task: Kubernetes@1
  displayName: Kubernetes container deploy
  inputs:
     connectionType: 'Kubernetes Service Connection'
     kubernetesServiceEndpoint: 'Connect kubernetes'
     namespace: 'default'
     command: 'apply'
     arguments: '-f kubernetes/deployment-testing-web.yaml'
     secretType: 'dockerRegistry'
     containerRegistryType: 'Azure Container Registry'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1(b5825397-99b4-4688-a061-129df71bbf2a)'
    azureResourceGroup: 'aks-getting-started'
    kubernetesCluster: 'aks-getting-started'
    namespace: 'default'
    command: 'expose'
    arguments: 'deployment devops-cristobal-deploy --type=LoadBalancer --name=pet-clinic'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
  continueOnError: true
  displayName: Expose deployment
